---

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install container networking package
  ansible.builtin.apt:
    name: containernetworking-plugins
    state: present
